openapi: 3.2.0
info:
  title: Prior Authorization v1 Authorization (Orchestration) API
  description: ''
  version: 1.1.0
  contact:
    email: ''
servers:
- url: https://sandbox-apigw.optum.com/rcm/prior-authorization/v1/
- url: /processor
security:
- bearerAuth: []
tags:
- name: Authorization (Orchestration)
paths:
  /authorization/x12:
    post:
      summary: 278x215 Prior Authorization Orchestration
      description: Prior authorization orchestration using EDI X12 278x215 requests
      tags:
      - Authorization (Orchestration)
      parameters:
      - $ref: '#/components/parameters/x-optum-tenant-id'
      - $ref: '#/components/parameters/x-optum-correlation-id'
      requestBody:
        description: Authorization request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationX12Request'
            examples:
              required-and-not-required:
                $ref: '#/components/examples/X12OrchRequestTwoCodesOneRequired'
              required-with-split:
                $ref: '#/components/examples/X12OrchRequestTwoRequiredCodesWithSplit'
              no-procedure-codes:
                $ref: '#/components/examples/X12OrchRequestNoProcedureCodes'
      responses:
        '200':
          description: Success
          headers:
            x-amzn-trace-id:
              $ref: '#/components/headers/x-amzn-trace-id'
            transaction-id:
              $ref: '#/components/headers/transaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  /authorization:
    post:
      summary: JSON Prior Authorization Orchestration
      description: Prior authorization orchestration using JSON requests
      tags:
      - Authorization (Orchestration)
      parameters:
      - $ref: '#/components/parameters/x-optum-tenant-id'
      - $ref: '#/components/parameters/x-optum-correlation-id'
      requestBody:
        description: Authorization request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InquiryJSONRequestWithDetermination'
            examples:
              inquiry-split:
                $ref: '#/components/examples/OrchestrationJSONRequestWithSplit'
              single-requires-pa:
                $ref: '#/components/examples/OrchestrationJSONRequestOneRequired'
              none-require-pa:
                $ref: '#/components/examples/OrchestrationJSONRequestAuthNotRequired'
      responses:
        '200':
          description: Success
          headers:
            x-amzn-trace-id:
              $ref: '#/components/headers/x-amzn-trace-id'
            transaction-id:
              $ref: '#/components/headers/transaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
components:
  headers:
    transaction-id:
      description: Transaction Id of the request
      required: true
      schema:
        type: string
        format: uuid
        example: c9476bc2-b563-4555-9527-4afe9dccaf9a
    x-amzn-trace-id:
      description: Generated traceId of the request
      required: true
      example: Root=1-61d7441a-56e4c77350687b5230e5707
      schema:
        type: string
  examples:
    X12OrchRequestNoProcedureCodes:
      summary: X12 Orchestration - No procedure codes require auth
      value:
        rhPayerId: UHCDEMODV1
        planId: '41'
        x12: ISA*00*          *00*          *ZZ*201985AAS      *ZZ*UHCDIRECT      *260220*2231*^*00501*310114548*0*P*:~GS*HI*201985AAS*UHCDIRECT*20260220*223147*549621530*X*005010X215~ST*278*0001*005010X215~BHT*0007*28*1234567890*20260220*223147~HL*1**20*1~NM1*PR*2*UHCDIRECT*****PI*UHCDIRECT~HL*2*1*21*1~NM1*1P*2*Regional Medical Center*****XX*1234567890~REF*EI*123456789~N4*Orangeburg*SC*12345~PER*IC**TE*803-555-2200~HL*3*2*22*1~NM1*IL*1*TEST*BRITTANY****MI*multi-01-approved~REF*6P*123456789~REF*SY*111223333~DMG*D8*19701231~HL*4*3*EV*1~UM*HS*I*1*11:B~DTP*AAH*RD8*20231017-20231017~NM1*SJ*1*TEST*STEVEN****XX*1234567890~NM1*DN*1*TEST*STEVEN****XX*1234567890~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:6789T~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:9876T~SE*28*0001~GE*1*549621530~IEA*1*310114548~
    X12OrchRequestTwoRequiredCodesWithSplit:
      summary: X12 Orchestration - Two procedure codes require auth with split
      value:
        rhPayerId: UHCDEMODV1
        planId: '41'
        x12: ISA*00*          *00*          *ZZ*201985AAS      *ZZ*UHCDIRECT      *260220*2231*^*00501*310114548*0*P*:~GS*HI*201985AAS*UHCDIRECT*20260220*223147*549621530*X*005010X215~ST*278*0001*005010X215~BHT*0007*28*1234567890*20260220*223147~HL*1**20*1~NM1*PR*2*UHCDIRECT*****PI*UHCDIRECT~HL*2*1*21*1~NM1*1P*2*Regional Medical Center*****XX*1234567890~REF*EI*123456789~N4*Orangeburg*SC*12345~PER*IC**TE*803-555-2200~HL*3*2*22*1~NM1*IL*1*TEST*BRITTANY****MI*multi-01-approved~REF*6P*123456789~REF*SY*111223333~DMG*D8*19701231~HL*4*3*EV*1~UM*HS*I*1*11:B~DTP*AAH*RD8*20231017-20231017~NM1*SJ*1*TEST*STEVEN****XX*1234567890~NM1*DN*1*TEST*STEVEN****XX*1234567890~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:T1000~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:0214T~SE*28*0001~GE*1*549621530~IEA*1*310114548~
    X12OrchRequestTwoCodesOneRequired:
      summary: X12 Orchestration - Two procedure codes; one requires auth
      value:
        rhPayerId: UHCDEMODV1
        planId: '41'
        x12: ISA*00*          *00*          *ZZ*201985AAS      *ZZ*UHCDIRECT      *260220*2231*^*00501*310114548*0*P*:~GS*HI*201985AAS*UHCDIRECT*20260220*223147*549621530*X*005010X215~ST*278*0001*005010X215~BHT*0007*28*1234567890*20260220*223147~HL*1**20*1~NM1*PR*2*UHCDIRECT*****PI*UHCDIRECT~HL*2*1*21*1~NM1*1P*2*Regional Medical Center*****XX*1234567890~REF*EI*123456789~N4*Orangeburg*SC*12345~PER*IC**TE*803-555-2200~HL*3*2*22*1~NM1*IL*1*TEST*BRITTANY****MI*multi-01-approved~REF*6P*123456789~REF*SY*111223333~DMG*D8*19701231~HL*4*3*EV*1~UM*HS*I*1*11:B~DTP*AAH*RD8*20231017-20231017~NM1*SJ*1*TEST*STEVEN****XX*1234567890~NM1*DN*1*TEST*STEVEN****XX*1234567890~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:T1000~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:9876T~SE*28*0001~GE*1*549621530~IEA*1*310114548~
    OrchestrationJSONRequestAuthNotRequired:
      summary: JSON Orchestration - No procedure codes require auth
      value:
        senderId: 201985AAS
        submitterTransactionIdentifier: '1234567890'
        payerId: BCBSSC
        payerName: South Carolina Blue Cross Blue
        rhPayerId: UHCDEMODV1
        planId: '41'
        umClearingHouseId: UHCDIRECT
        requester:
          requesterType: 1P
          organizationName: Regional Medical Center
          lastName: Regional Medical Center
          requesterIdentification:
            employerIdentificationNumber: '123456789'
          city: Orangeburg
          state: SC
          postalCode: '12345'
          npi: '1234567890'
          contactTelephone: '8033952200'
        subscriber:
          lastName: TEST
          firstName: BRITTANY
          memberId: multi-01-approved
          dateOfBirth: '19701231'
          supplementalIdentification:
            groupNumber: '123456789'
            ssn: '111223333'
        patientEventDetail:
          requestCategoryCode: HS
          certificationTypeCode: I
          serviceTypeCode: '1'
          facilityTypeCode: '11'
          facilityCodeQualifier: B
          eventDateBegin: '20231017'
          eventDateEnd: '20231017'
          patientEventProviderName:
          - entityIdentifierCode: SJ
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          - entityIdentifierCode: DN
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          serviceLevel:
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: 6789T
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: 9876T
    OrchestrationJSONRequestWithSplit:
      summary: JSON Orchestration - Two procedure codes require auth with split
      value:
        senderId: 201985AAS
        submitterTransactionIdentifier: '1234567890'
        payerId: BCBSSC
        payerName: South Carolina Blue Cross Blue
        rhPayerId: UHCDEMODV1
        planId: '41'
        umClearingHouseId: UHCDIRECT
        requester:
          requesterType: 1P
          organizationName: Regional Medical Center
          lastName: Regional Medical Center
          requesterIdentification:
            employerIdentificationNumber: '123456789'
          city: Orangeburg
          state: SC
          postalCode: '12345'
          npi: '1234567890'
          contactTelephone: '8033952200'
        subscriber:
          lastName: TEST
          firstName: BRITTANY
          memberId: multi-01-approved
          dateOfBirth: '19701231'
          supplementalIdentification:
            groupNumber: '123456789'
            ssn: '111223333'
        patientEventDetail:
          requestCategoryCode: HS
          certificationTypeCode: I
          serviceTypeCode: '1'
          facilityTypeCode: '11'
          facilityCodeQualifier: B
          eventDateBegin: '20231017'
          eventDateEnd: '20231017'
          patientEventProviderName:
          - entityIdentifierCode: SJ
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          - entityIdentifierCode: DN
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          serviceLevel:
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: T1000
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: 0214T
    OrchestrationJSONRequestOneRequired:
      summary: JSON Orchestration - Two procedure codes; one requires auth
      value:
        senderId: 201985AAS
        submitterTransactionIdentifier: '1234567890'
        payerId: BCBSSC
        payerName: South Carolina Blue Cross Blue
        rhPayerId: UHCDEMODV1
        planId: '41'
        umClearingHouseId: UHCDIRECT
        requester:
          requesterType: 1P
          organizationName: Regional Medical Center
          lastName: Regional Medical Center
          requesterIdentification:
            employerIdentificationNumber: '123456789'
          city: Orangeburg
          state: SC
          postalCode: '12345'
          npi: '1234567890'
          contactTelephone: '8033952200'
        subscriber:
          lastName: TEST
          firstName: BRITTANY
          memberId: multi-01-approved
          dateOfBirth: '19701231'
          supplementalIdentification:
            groupNumber: '123456789'
            ssn: '111223333'
        patientEventDetail:
          requestCategoryCode: HS
          certificationTypeCode: I
          serviceTypeCode: '1'
          facilityTypeCode: '11'
          facilityCodeQualifier: B
          eventDateBegin: '20231017'
          eventDateEnd: '20231017'
          patientEventProviderName:
          - entityIdentifierCode: SJ
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          - entityIdentifierCode: DN
            lastName: TEST
            firstName: STEVEN
            identificationCodeQualifier: XX
            identifier: '1234567890'
          serviceLevel:
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: T1000
          - requestCategoryCode: HS
            facilityTypeCode: '11'
            facilityCodeQualifier: B
            serviceDateBegin: '20231017'
            serviceDateEnd: '20231017'
            professionalService:
              productOrServiceIDQualifier: HC
              procedureCode: 9876T
  schemas:
    InquiryJSONRequestWithDetermination:
      allOf:
      - $ref: '#/components/schemas/InquiryJSONRequest'
      - type: object
        properties:
          rhPayerId:
            type: string
            description: Global payer identifier used for determination
            example: UHCDEMODV1
          planId:
            type: string
            description: Payer plan identifier used for determination
            example: '41'
    AuthorizationResponse:
      type: object
      properties:
        authorizationId:
          type: string
        determination:
          type: object
          properties:
            x12:
              type: string
            json:
              $ref: '#/components/schemas/AuthorizationJSONResponse'
        inquiry:
          type: array
          maxItems: 100
          items:
            type: object
            properties:
              x12:
                type: string
              json:
                $ref: '#/components/schemas/AuthorizationJSONResponse'
    AuthorizationJSONResponse:
      type: object
      properties:
        requestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        submitterTransactionIdentifier:
          type: string
        payerId:
          type: string
        payerName:
          type: string
        umClearingHouseId:
          type: string
        contactName:
          type: string
        contactElectronicMail:
          type: string
        contactFacsimile:
          type: string
        contactTelephone:
          type: string
        contactTelephoneExtension:
          type: string
        contactUrl:
          type: string
        umRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        requester:
          $ref: '#/components/schemas/AuthorizationJSONResponseRequester'
        subscriber:
          $ref: '#/components/schemas/AuthorizationJSONResponseSubscriber'
        dependent:
          $ref: '#/components/schemas/AuthorizationJSONResponseDependent'
        patientEventDetail:
          $ref: '#/components/schemas/AuthorizationJSONResponsePatientEventDetail'
    AuthorizationJSONResponsePatientEventDetail:
      type: object
      properties:
        dependentRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        requestCategoryCode:
          type: string
        certificationTypeCode:
          type: string
        serviceTypeCode:
          type: string
        facilityTypeCode:
          type: string
        facilityCodeQualifier:
          type: string
        certificationActionCode:
          type: string
        reviewIdentificationNumber:
          type: string
        reviewDecisionReasonCode:
          type: string
        secondSurgicalOpinionIndicator:
          type: string
        previousReviewAuthorizationNumber:
          type: string
        previousAdministrativeReferenceNumber:
          type: string
        eventDateBegin:
          type: string
        eventDateEnd:
          type: string
        admissionDateBegin:
          type: string
        admissionDateEnd:
          type: string
        dischargeDate:
          type: string
        certificationIssueDate:
          type: string
        certificationExpirationDate:
          type: string
        certificationEffectiveDateBegin:
          type: string
        certificationEffectiveDateEnd:
          type: string
        healthCareServicesReviewRequestDateBegin:
          type: string
        healthCareServicesReviewRequestDateEnd:
          type: string
        diagnosisTypeCode:
          type: string
        diagnosisCode:
          type: string
        quantityQualifier:
          type: string
        serviceUnitCount:
          type: string
        unitOrBasisForMeasurementCode:
          type: string
        sampleSelectionModulus:
          type: string
        timePeriodQualifier:
          type: string
        periodCount:
          type: string
        deliveryFrequencyCode:
          type: string
        deliveryPatternTimeCode:
          type: string
        institutionalAdmissionTypeCode:
          type: string
        institutionalAdmissionSourceCode:
          type: string
        institutionalPatientStatusCode:
          type: string
        ambulanceTransportCode:
          type: string
        ambulanceUnitOrBasisForMeasurementCode:
          type: string
        ambulanceTransportDistance:
          type: string
        spinalManipulationTreatmentSeriesNumber:
          type: string
        spinalManipulationTreatmentCount:
          type: string
        spinalManipulationSubluxationLevelCode:
          type: string
        spinalManipulationSubluxationLevelCode2:
          type: string
        oxygenEquipmentTypeCode:
          type: string
        oxygenEquipmentTypeCode2:
          type: string
        oxygenFlowRate:
          type: string
        dailyOxygenUseCount:
          type: string
        oxygenUsePeriodHourCount:
          type: string
        respiratoryTherapistOrderText:
          type: string
        portableOxygenSystemFlowRate:
          type: string
        oxygenDeliverySystemCode:
          type: string
        oxygenSystemTypeCode:
          type: string
        homeHealthPrognosisCode:
          type: string
        homeHealthStartDate:
          type: string
        homeHealthCertificationPeriod:
          type: string
        homeHealthMedicareCoverageIndicator:
          type: string
        homeHealthCertificationTypeCode:
          type: string
        freeFormMessageText:
          type: string
        patientEventProviderName:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponsePatientEventProviderName'
        patientEventTransportInformation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponsePatientEventTransportInformation'
        serviceLevel:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseServiceLevel'
    AuthorizationJSONResponsePatientEventTransportInformation:
      type: object
      properties:
        entityIdentifierCode:
          type: string
        organizationName:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
    AuthorizationJSONResponseRequestValidation:
      type: object
      properties:
        responseCode:
          type: string
        rejectReasonCode:
          type: string
        followupActionCode:
          type: string
    AuthorizationJSONResponseIonalService:
      type: object
      properties:
        serviceLineRevenueCode:
          type: string
        productOrServiceIDQualifier:
          type: string
        procedureCode:
          type: string
        procedureModifier:
          type: string
        procedureModifier2:
          type: string
        procedureModifier3:
          type: string
        procedureModifier4:
          type: string
        procedureCodeDescription:
          type: string
        procedureCode2:
          type: string
        serviceLineAmount:
          type: string
        unitOrBasisForMeasurementCode:
          type: string
        serviceUnitCount:
          type: string
        serviceLineRate:
          type: string
        epsdtIndicator:
          type: string
    AuthorizationJSONResponsePatientEventProviderName:
      type: object
      properties:
        patientEventProviderRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        entityIdentifierCode:
          type: string
        organizationName:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        namePrefix:
          type: string
        nameSuffix:
          type: string
        identificationCodeQualifier:
          type: string
        identifier:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
        countrySubDivisionCode:
          type: string
        providerSupplementalInformation:
          $ref: '#/components/schemas/AuthorizationJSONResponseProviderSupplementalInformation'
        contactName:
          type: string
        contactElectronicMail:
          type: string
        contactFacsimile:
          type: string
        contactTelephone:
          type: string
        contactTelephoneExtension:
          type: string
        contactUrl:
          type: string
        providerCode:
          type: string
        providerTaxonomyCode:
          type: string
    AuthorizationJSONResponseDependent:
      type: object
      properties:
        dependentRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        suffix:
          type: string
        dateOfBirth:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
        countrySubDivisionCode:
          type: string
        supplementalIdentification:
          $ref: '#/components/schemas/AuthorizationJSONResponseDependentSupplementalIdentification'
    InquiryJSONRequest:
      type: object
      properties:
        senderId:
          type: string
        submitterTransactionIdentifier:
          type: string
        payerId:
          type: string
        payerName:
          type: string
        umClearingHouseId:
          type: string
        requester:
          type: object
          properties:
            requesterType:
              type: string
            organizationName:
              type: string
            lastName:
              type: string
            firstName:
              type: string
            requesterIdentification:
              type: object
              properties:
                providerUpinNumber:
                  type: string
                facilityIdNumber:
                  type: string
                employerIdentificationNumber:
                  type: string
                providerSiteNumber:
                  type: string
                providerPlanNetworkIdNumber:
                  type: string
                facilityNetworkIdNumber:
                  type: string
                socialSecurityNumber:
                  type: string
                federalTaxpayerIdentificationNumber:
                  type: string
                carrierAssignedReferenceNumber:
                  type: string
            address1:
              type: string
            address2:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            countryCode:
              type: string
            countrySubDivisionCode:
              type: string
            npi:
              type: string
            payorId:
              type: string
            ssn:
              type: string
            servicesPlanID:
              type: string
            employersId:
              type: string
            etin:
              type: string
            contactName:
              type: string
            contactElectronicMail:
              type: string
            contactFacsimile:
              type: string
            contactTelephone:
              type: string
            contactTelephoneExtension:
              type: string
            providerCode:
              type: string
            referenceIdentification:
              type: string
        subscriber:
          type: object
          properties:
            lastName:
              type: string
            firstName:
              type: string
            middleName:
              type: string
            suffix:
              type: string
            memberId:
              type: string
            dateOfBirth:
              type: string
            supplementalIdentification:
              type: object
              properties:
                policyNumber:
                  type: string
                branchIdentifier:
                  type: string
                groupNumber:
                  type: string
                departmentNumber:
                  type: string
                patientAccountNumber:
                  type: string
                healthInsuranceClaimNumber:
                  type: string
                idCard:
                  type: string
                insurancePolicyNumber:
                  type: string
                planNetworkIdentificationNumber:
                  type: string
                medicaidRecipientIdentificationNumber:
                  type: string
                ssn:
                  type: string
        dependent:
          type: object
          properties:
            lastName:
              type: string
            firstName:
              type: string
            middleName:
              type: string
            suffix:
              type: string
            dateOfBirth:
              type: string
            supplementalIdentification:
              type: object
              properties:
                employeeIdentificationNumber:
                  type: string
                patientAccountNumber:
                  type: string
                ssn:
                  type: string
        patientEventDetail:
          type: object
          properties:
            requestCategoryCode:
              type: string
            certificationTypeCode:
              type: string
            serviceTypeCode:
              type: string
            facilityTypeCode:
              type: string
            facilityCodeQualifier:
              type: string
            certificationActionCode:
              type: string
            previousReviewAuthorizationNumber:
              type: string
            previousAdministrativeReferenceNumber:
              type: string
            accidentDate:
              type: string
            eventDateBegin:
              type: string
            eventDateEnd:
              type: string
            admissionDateBegin:
              type: string
            admissionDateEnd:
              type: string
            dischargeDate:
              type: string
            certificationIssueDateBegin:
              type: string
            certificationIssueDateEnd:
              type: string
            certificationExpirationDateBegin:
              type: string
            certificationExpirationDateEnd:
              type: string
            certificationEffectiveDateBegin:
              type: string
            certificationEffectiveDateEnd:
              type: string
            healthCareServicesReviewRequestDate:
              type: string
            diagnosisTypeCode:
              type: string
            diagnosisCode:
              type: string
            patientEventProviderName:
              type: array
              items:
                type: object
                properties:
                  entityIdentifierCode:
                    type: string
                  organizationName:
                    type: string
                  lastName:
                    type: string
                  firstName:
                    type: string
                  middleName:
                    type: string
                  namePrefix:
                    type: string
                  nameSuffix:
                    type: string
                  identificationCodeQualifier:
                    type: string
                  identifier:
                    type: string
                  address1:
                    type: string
                  address2:
                    type: string
                  city:
                    type: string
                  state:
                    type: string
                  postalCode:
                    type: string
                  countryCode:
                    type: string
                  countrySubDivisionCode:
                    type: string
                  providerSupplementalInformation:
                    type: object
                    properties:
                      stateLicenseNumber:
                        type: string
                      licenseNumberStateCode:
                        type: string
                      providerUpinNumber:
                        type: string
                      facilityIdNumber:
                        type: string
                      employersIdentificationNumber:
                        type: string
                      providerPlanNetworkIdentificationNumber:
                        type: string
                      facilityNetworkIdentificationNumber:
                        type: string
                      ssn:
                        type: string
                      carrierAssignedReferenceNumber:
                        type: string
                  providerCode:
                    type: string
                  providerTaxonomyCode:
                    type: string
            serviceLevel:
              type: array
              items:
                type: object
                properties:
                  requestCategoryCode:
                    type: string
                  certificationTypeCode:
                    type: string
                  serviceTypeCode:
                    type: string
                  facilityTypeCode:
                    type: string
                  facilityCodeQualifier:
                    type: string
                  certificationActionCode:
                    type: string
                  previousReviewAuthorizationNumber:
                    type: string
                  previousAdministrativeReferenceNumber:
                    type: string
                  serviceDateBegin:
                    type: string
                  serviceDateEnd:
                    type: string
                  certificationIssueDateBegin:
                    type: string
                  certificationIssueDateEnd:
                    type: string
                  certificationExpirationDateBegin:
                    type: string
                  certificationExpirationDateEnd:
                    type: string
                  certificationEffectiveDateBegin:
                    type: string
                  certificationEffectiveDateEnd:
                    type: string
                  professionalService:
                    type: object
                    properties:
                      productOrServiceIDQualifier:
                        type: string
                      procedureCode:
                        type: string
                      procedureCode2:
                        type: string
                      unitOrBasisForMeasurementCode:
                        type: string
                      serviceUnitCount:
                        type: string
                  institutionalService:
                    type: object
                    properties:
                      serviceLineRevenueCode:
                        type: string
                      productOrServiceIDQualifier:
                        type: string
                      procedureCode:
                        type: string
                      procedureCode2:
                        type: string
                      unitOrBasisForMeasurementCode:
                        type: string
                      serviceUnitCount:
                        type: string
                  dentalService:
                    type: object
                    properties:
                      procedureCode:
                        type: string
                      procedureCode2:
                        type: string
                      americanDentalAssociationCodes:
                        type: string
                      prosthesisCrownOrInlayCode:
                        type: string
                      serviceUnitCount:
                        type: string
                  toothInformation:
                    type: object
                    properties:
                      toothCode:
                        type: string
                      toothSurfaceCode:
                        type: string
                  serviceProviderName:
                    type: array
                    items:
                      type: object
                      properties:
                        entityIdentifierCode:
                          type: string
                        organizationName:
                          type: string
                        lastName:
                          type: string
                        firstName:
                          type: string
                        middleName:
                          type: string
                        namePrefix:
                          type: string
                        nameSuffix:
                          type: string
                        identificationCodeQualifier:
                          type: string
                        identifier:
                          type: string
                        address1:
                          type: string
                        address2:
                          type: string
                        city:
                          type: string
                        state:
                          type: string
                        postalCode:
                          type: string
                        countryCode:
                          type: string
                        countrySubDivisionCode:
                          type: string
                        providerSupplementalInformation:
                          type: object
                          properties:
                            stateLicenseNumber:
                              type: string
                            licenseNumberStateCode:
                              type: string
                            providerUpinNumber:
                              type: string
                            facilityIdNumber:
                              type: string
                            employersIdentificationNumber:
                              type: string
                            providerSiteNumber:
                              type: string
                            providerPlanNetworkIdentificationNumber:
                              type: string
                            facilityNetworkIdentificationNumber:
                              type: string
                            ssn:
                              type: string
                            carrierAssignedReferenceNumber:
                              type: string
                        providerCode:
                          type: string
                        providerTaxonomyCode:
                          type: string
    AuthorizationJSONResponseDependentSupplementalIdentification:
      type: object
      additionalProperties: false
      properties:
        employeeIdentificationNumber:
          type: string
        patientAccountNumber:
          type: string
        ssn:
          type: string
    AuthorizationJSONResponseServiceLevel:
      type: object
      properties:
        serviceRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        requestCategoryCode:
          type: string
        certificationTypeCode:
          type: string
        serviceTypeCode:
          type: string
        facilityTypeCode:
          type: string
        facilityCodeQualifier:
          type: string
        certificationActionCode:
          type: string
        reviewIdentificationNumber:
          type: string
        reviewDecisionReasonCode:
          type: string
        secondSurgicalOpinionIndicator:
          type: string
        previousReviewAuthorizationNumber:
          type: string
        previousAdministrativeReferenceNumber:
          type: string
        serviceDateBegin:
          type: string
        serviceDateEnd:
          type: string
        certificationIssueDate:
          type: string
        certificationExpirationDate:
          type: string
        certificationEffectiveDateBegin:
          type: string
        certificationEffectiveDateEnd:
          type: string
        professionalService:
          $ref: '#/components/schemas/AuthorizationJSONResponseIonalService'
        institutionalService:
          $ref: '#/components/schemas/AuthorizationJSONResponseIonalService'
        dentalService:
          $ref: '#/components/schemas/AuthorizationJSONResponseDentalService'
        toothInformation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseToothInformation'
        quantityQualifier:
          type: string
        serviceUnitCount:
          type: string
        unitOrBasisForMeasurementCode:
          type: string
        sampleSelectionModulus:
          type: string
        timePeriodQualifier:
          type: string
        periodCount:
          type: string
        deliveryFrequencyCode:
          type: string
        deliveryPatternTimeCode:
          type: string
        freeFormMessageText:
          type: string
        serviceProviderName:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseServiceProviderName'
    AuthorizationJSONResponseRequesterIdentification:
      type: object
      properties:
        providerUpinNumber:
          type: string
        facilityIdNumber:
          type: string
        employerIdentificationNumber:
          type: string
        providerSiteNumber:
          type: string
        providerPlanNetworkIdNumber:
          type: string
        facilityNetworkIdNumber:
          type: string
        socialSecurityNumber:
          type: string
        carrierAssignedReferenceNumber:
          type: string
    AuthorizationJSONResponseRequester:
      type: object
      properties:
        requesterRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        requesterType:
          type: string
        organizationName:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        requesterIdentification:
          $ref: '#/components/schemas/AuthorizationJSONResponseRequesterIdentification'
        npi:
          type: string
        payorId:
          type: string
        ssn:
          type: string
        servicesPlanID:
          type: string
        employersId:
          type: string
        etin:
          type: string
        providerCode:
          type: string
        referenceIdentification:
          type: string
    AuthorizationJSONResponseProviderSupplementalInformation:
      type: object
      properties:
        stateLicenseNumber:
          type: string
        licenseNumberStateCode:
          type: string
        providerUpinNumber:
          type: string
        facilityIdNumber:
          type: string
        employersIdentificationNumber:
          type: string
        providerPlanNetworkIdentificationNumber:
          type: string
        facilityNetworkIdentificationNumber:
          type: string
        ssn:
          type: string
        carrierAssignedReferenceNumber:
          type: string
        providerSiteNumber:
          type: string
    AuthorizationJSONResponseDentalService:
      type: object
      properties:
        procedureCode:
          type: string
        procedureModifier:
          type: string
        procedureModifier2:
          type: string
        procedureModifier3:
          type: string
        procedureModifier4:
          type: string
        procedureCodeDescription:
          type: string
        procedureCode2:
          type: string
        serviceLineAmount:
          type: string
        americanDentalAssociationCodes:
          type: string
        americanDentalAssociationCodes2:
          type: string
        americanDentalAssociationCodes3:
          type: string
        americanDentalAssociationCodes4:
          type: string
        americanDentalAssociationCodes5:
          type: string
        prosthesisCrownOrInlayCode:
          type: string
        serviceUnitCount:
          type: string
    Errors:
      type: array
      items:
        type: string
        example: This is an example error string
    AuthorizationJSONResponseSubscriberSupplementalIdentification:
      type: object
      properties:
        policyNumber:
          type: string
        branchIdentifier:
          type: string
        groupNumber:
          type: string
        departmentNumber:
          type: string
        patientAccountNumber:
          type: string
        healthInsuranceClaimNumber:
          type: string
        idCard:
          type: string
        insurancePolicyNumber:
          type: string
        planNetworkIdentificationNumber:
          type: string
        medicaidRecipientIdentificationNumber:
          type: string
        ssn:
          type: string
    AuthorizationJSONResponseToothInformation:
      type: object
      properties:
        toothCode:
          type: string
        toothSurfaceCode:
          type: string
        toothSurfaceCode2:
          type: string
        toothSurfaceCode3:
          type: string
        toothSurfaceCode4:
          type: string
        toothSurfaceCode5:
          type: string
    AuthorizationJSONResponseServiceProviderName:
      type: object
      properties:
        serviceProviderRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        entityIdentifierCode:
          type: string
        organizationName:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        namePrefix:
          type: string
        nameSuffix:
          type: string
        identificationCodeQualifier:
          type: string
        identifier:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
        countrySubDivisionCode:
          type: string
        providerSupplementalInformation:
          $ref: '#/components/schemas/AuthorizationJSONResponseProviderSupplementalInformation'
        contactName:
          type: string
        contactElectronicMail:
          type: string
        contactFacsimile:
          type: string
        contactTelephone:
          type: string
        contactTelephoneExtension:
          type: string
        contactUrl:
          type: string
        providerCode:
          type: string
        providerTaxonomyCode:
          type: string
    AuthorizationJSONResponseSubscriber:
      type: object
      properties:
        subscriberRequestValidation:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationJSONResponseRequestValidation'
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        suffix:
          type: string
        memberId:
          type: string
        dateOfBirth:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
        countrySubDivisionCode:
          type: string
        supplementalIdentification:
          $ref: '#/components/schemas/AuthorizationJSONResponseSubscriberSupplementalIdentification'
    AuthorizationX12Request:
      type: object
      properties:
        rhPayerId:
          type: string
          description: Global payer identifier used for determination
          example: UHCDEMODV1
        planId:
          type: string
          description: Payer plan identifier used for determination
          example: 41
        x12:
          type: string
          description: EDI X12 278x215 Request
          example: ISA*00*          *00*          *ZZ*201985AAS      *ZZ*UHCDIRECT      *260220*2231*^*00501*310114548*0*P*:~GS*HI*201985AAS*UHCDIRECT*20260220*223147*549621530*X*005010X215~ST*278*0001*005010X215~BHT*0007*28*1234567890*20260220*223147~HL*1**20*1~NM1*PR*2*UHCDIRECT*****PI*UHCDIRECT~HL*2*1*21*1~NM1*1P*2*Regional Medical Center*****XX*1234567890~REF*EI*123456789~N4*Orangeburg*SC*12345~PER*IC**TE*803-555-2200~HL*3*2*22*1~NM1*IL*1*TEST*BRITTANY****MI*multi-01-approved~REF*6P*123456789~REF*SY*111223333~DMG*D8*19701231~HL*4*3*EV*1~UM*HS*I*1*11:B~DTP*AAH*RD8*20231017-20231017~NM1*SJ*1*TEST*STEVEN****XX*1234567890~NM1*DN*1*TEST*STEVEN****XX*1234567890~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:T1000~HL*5*4*SS*0~UM*HS***11:B~DTP*472*RD8*20231017-20231017~SV1*HC:0214T~SE*28*0001~GE*1*549621530~IEA*1*310114548~
  responses:
    '403':
      headers:
        x-amzn-trace-id:
          $ref: '#/components/headers/x-amzn-trace-id'
      description: Forbidden. Authentication succeeded but authenticated user doesn't have access to the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '401':
      description: Unauthorized. No or invalid authentication details are provided
      headers:
        x-amzn-trace-id:
          $ref: '#/components/headers/x-amzn-trace-id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '400':
      headers:
        x-amzn-trace-id:
          $ref: '#/components/headers/x-amzn-trace-id'
      description: Bad Request. The request body is malformed or missing required information.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      headers:
        x-amzn-trace-id:
          $ref: '#/components/headers/x-amzn-trace-id'
      description: Internal Server Error. An unexpected error has occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    x-optum-tenant-id:
      description: The unique ID of the tenant that the invoking user belongs to.
      in: header
      name: x-optum-tenant-id
      schema:
        type: string
        format: uuid
        example: 9fb77454-8c58-4345-aa50-43f133e06d20
      required: true
    x-optum-correlation-id:
      description: A unique identifier assigned to each request.
      in: header
      name: x-optum-correlation-id
      schema:
        type: string
        format: uuid
        example: c9476bc2-b563-4555-9527-4afe9dccaf9a
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
